import "@fortawesome/fontawesome-svg-core/styles.css";
import "@mantine/core/styles.layer.css";
import "@mantine/dates/styles.layer.css";
import "@mantine/notifications/styles.layer.css";
import "dayjs/locale/pt-br";
import "mantine-datatable/styles.layer.css";
import "~/styles/globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { Inter } from "next/font/google";
import { DateProvider } from "~/providers/DateProvider";
import { ReactQueryProvider } from "~/providers/ReactQueryProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

config.autoAddCss = false;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body className={`font-sans ${inter.variable}`}>
        <ReactQueryProvider>
          <MantineProvider defaultColorScheme="auto" theme={{ fontFamily: "Lato" }}>
            <DateProvider>
              <Notifications />
              {children}
            </DateProvider>
          </MantineProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
